#!/usr/bin/env bash
set -euo pipefail

CODE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$CODE_ROOT/.." && pwd)"
LOG_ROOT="$REPO_ROOT/descargas/logs"

EXPERIMENT_MODULE="${EXPERIMENT_MODULE:?Set EXPERIMENT_MODULE}"
BETA1S_CSV="${BETA1S_CSV:?Set BETA1S_CSV}"
BETA2S_CSV="${BETA2S_CSV:-$BETA1S_CSV}"
SEEDS_CSV="${SEEDS_CSV:?Set SEEDS_CSV}"
PYTHON_BIN="${PYTHON_BIN:-python}"
PARTITION="${PARTITION:-q5}"
CPUS="${CPUS:-8}"
MEM="${MEM:-64G}"
GRES="${GRES:-gpu:1}"
ARRAY_CONCURRENCY="${ARRAY_CONCURRENCY:-}"
DATA_ROOT="${DATA_ROOT:-/scratch1/hernanal/datasets}"
RUNTIME_ASSETS_DIR="${RUNTIME_ASSETS_DIR:-$CODE_ROOT/runtime_assets}"
KAGGLE_JSON_PATH="${KAGGLE_JSON_PATH:-$RUNTIME_ASSETS_DIR/kaggle.json}"

IFS=',' read -r -a BETA1S <<< "$BETA1S_CSV"
IFS=',' read -r -a BETA2S <<< "$BETA2S_CSV"
IFS=',' read -r -a SEEDS <<< "$SEEDS_CSV"
ARRAY_MAX=$(( ${#BETA1S[@]} * ${#BETA2S[@]} * ${#SEEDS[@]} - 1 ))
ARRAY_SPEC="0-${ARRAY_MAX}"
if [[ -n "$ARRAY_CONCURRENCY" ]]; then
  ARRAY_SPEC="${ARRAY_SPEC}%${ARRAY_CONCURRENCY}"
fi

mkdir -p "$LOG_ROOT/$EXPERIMENT_MODULE"

sbatch \
  --partition "$PARTITION" \
  --nodes 1 \
  --cpus-per-task "$CPUS" \
  --mem "$MEM" \
  --gres "$GRES" \
  --job-name "$EXPERIMENT_MODULE" \
  --array "$ARRAY_SPEC" \
  --output "$LOG_ROOT/$EXPERIMENT_MODULE/slurm_%A_%a.out" \
  --export "ALL,REPO_ROOT=$REPO_ROOT,CODE_ROOT=$CODE_ROOT,LOG_ROOT=$LOG_ROOT,PYTHON_BIN=$PYTHON_BIN,EXPERIMENT_MODULE=$EXPERIMENT_MODULE,BETA1S_CSV=$BETA1S_CSV,BETA2S_CSV=$BETA2S_CSV,SEEDS_CSV=$SEEDS_CSV,KAGGLE_JSON_PATH=${KAGGLE_JSON_PATH:-},DATA_ROOT=$DATA_ROOT,TRAINING_DATA_DIR=$DATA_ROOT,HF_HOME=$DATA_ROOT/hf_cache,HF_DATASETS_CACHE=$DATA_ROOT/hf_cache/datasets,HF_HUB_CACHE=$DATA_ROOT/hf_cache/hub,TRANSFORMERS_CACHE=$DATA_ROOT/hf_cache/transformers,TORCH_HOME=$DATA_ROOT/torch_cache" \
  "$CODE_ROOT/launchers/slurm_array_runner.sh"
